# Processor architecture
ARCH		= i686

# Paths
ETC_DIR		= /usr/local/etc/ax25
SBIN_DIR	= /usr/local/sbin
BIN_DIR		= /usr/local/bin
LIB_DIR		= /usr/local/lib
MAN_DIR		= /usr/local/share/man
VAR_DIR		= /usr/local/var/ax25

# Is Zlib available?
ZLIB		= -lz